name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build .class
        run: mvn compile

      - name: Build .jar
        run: mvn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: StarWorldEchoCave
          path: target/*.jar
